@startuml
interface Function {
    + print(): String
    + evaluate(Map<String, Function> variables): double
    + getVariables(): List<String>
}

class Value implements Function{
    value: double
}

class Variable implements Function{
    variable: string
}

class Addition implements Function{
    function1: Function
    function2: Function
}

class Subtraction implements Function{
    function1: Function
    function2: Function
}

class Multiplication implements Function{
    function1: Function
    function2: Function
}

class Division implements Function{
    function1: Function
    function2: Function
}

class SquareRoot implements Function{
    function1: Function
}

class Power implements Function{
    function1: Function
    function2: Function
}

class Absolute implements Function{
    function1: Function
}


@enduml

class Negate implements Function{
       value: Function
   }